POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY0MGZjNzAyOGRmNDE4NzM2YjU5MDZjNiIsImlhdCI6MTY3ODc1ODU0NH0.cnIQLp3khzZqO5Q9_qMvp4eX3vQzDq_w0cZub_YJJiE

{
    "title":"Authorization login Works",
    "author": "Jacob",
    "url":"www.google.com",
    "likes":10
}