POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"I can make notes with a user",
    "author": "Jacob",
    "url":"www.google.com",
    "likes":10,
    "userId": "640fc7028df418736b5906c6"
}